[package]
name = "pinned-aur-2"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.49", features = ["derive"] }
colored = "3.0.0"
reqwest = { version = "0.12.24", features = ["blocking", "json"] }
serde = "1.0.228"
